### Data Collection

This project aims to observe, and experiment with *Penny Stocks*. *yfinance* library was utilised to downloaded the data, also the ticker seleccion was obtained from the website.
The criteria for ticker seleccion correspond to stocks with a Price(day) below $5, a Volume more than 100k, and New York Stock Exchange (NYSE) and NASDAQ as Exchange.

In [3]:
from pathlib import Path
from datetime import datetime, timezone

import numpy as np
import pandas as pd
import yfinance as yf

In [16]:
page1 = ['ABEV', 'ABOS', 'ABR', 'ABUS', 'ACCO', 'ACDC', 'ACH', 'ACHR', 'ACP', 'ACRE', 'ACRS', 'ADCT', 'AIV', 'ALEC', 'ALLO', 'ALXO', 'AMBP', 'AMC', 'AMPY', 'AMTD', 'ANGX', 'ANNX', 'ANTX', 'ANVS', 'API', 'ASG', 'ASGI-RI', 'AUR', 'AUTL', 'AVAL', 'AVD', 'AVIR', 'AVXL', 'BAK', 'BBAI', 'BBBYW', 'BBD', 'BBDO', 'BCAT-RI', 'BCYC', 'BDN', 'BDTX', 'BGS', 'BHR', 'BIRD', 'BLND', 'BMEA', 'BORR', 'BRSP', 'BUR', 'BW', 'BZUN', 'CABA', 'CANG', 'CCCC', 'CCIF', 'CCO', 'CDXS', 'CGC', 'CHGG', 'CIG', 'CLNE', 'CLOV', 'CLVT', 'CMTG', 'CMTL', 'CNDT', 'COTY', 'COUR', 'CRBU', 'CRMT', 'CRNT', 'CSHR', 'CTMX', 'CVGI', 'CVRX', 'CWH', 'CYH', 'DDD', 'DDL', 'DHF', 'DHX', 'DNUT', 'DOUG', 'DSX', 'DWSN', 'EARN', 'ECC', 'EDF', 'EDIT', 'EGHT', 'EHTH', 'ELME', 'ENHA', 'ENIC', 'ENVX', 'ESRT', 'EVEX', 'EVGO', 'EVH']

In [17]:
page2 = ['EVO', 'EVTL', 'EXFY', 'FEAM', 'FINV', 'FIP', 'FLWS', 'FLX', 'FPH', 'FRMI', 'FSCO', 'GCTS', 'GDRX', 'GEMI', 'GERN', 'GETY', 'GGT', 'GLAS', 'GLOO', 'GME-WT', 'GOGO', 'GOTU', 'GPRO', 'GRAB', 'GRNT', 'GSIT', 'GT', 'GTM', 'GTN', 'HCAT', 'HEPS', 'HIO', 'HIX', 'HKD', 'HLLY', 'HRZN', 'HTT', 'HTZ', 'HUMA', 'HUYA', 'ICL', 'IFRX', 'IHRT', 'IMSR', 'IQ', 'IRWD', 'JBI', 'JBLU', 'JELD', 'JOBY', 'JQC', 'JRVR', 'KLC', 'KLTR', 'KNDI', 'KOS', 'KPTI', 'LAB', 'LAC', 'LAES', 'LAR', 'LCID', 'LDI', 'LENZ', 'LGO', 'LOT', 'LPL', 'LU', 'LX', 'LZM', 'MBI', 'MERC', 'METCB', 'MFM', 'MGNX', 'MGX', 'MIST', 'MLCO', 'MMT', 'MOMO', 'MPT', 'MX', 'MXCT', 'MYGN', 'NABL', 'NCMI', 'NFE', 'NIO', 'NKTX', 'NMCO-RI', 'NMG', 'NMRA', 'NNBR', 'NPWR', 'NRGV', 'NRO', 'NUVB', 'NXDR', 'NXH', 'OCAC-RI']

In [18]:
page3 = ['OGG', 'OGI', 'ONL', 'OPEN', 'OPENL', 'OPENW', 'OPENZ', 'OPK', 'OPTU', 'OSUR', 'OWLT', 'OXSQ', 'PACB', 'PACK', 'PAL', 'PEPG', 'PERF', 'PETS', 'PEW', 'PHK', 'PLCE', 'PLRX', 'PLTK', 'PMVP', 'PNNT', 'PRLD', 'PSEC', 'PTLO', 'PYXS', 'QS', 'RBBN', 'RC', 'RCS', 'RERE', 'RGP', 'RLX', 'RWT', 'RXRX', 'RXT', 'SABR', 'SANA', 'SEATW', 'SES', 'SFIX', 'SID', 'SITC', 'SJT', 'SKYD-WT', 'SKYD-WT-WI', 'SLDP', 'SLQT', 'SMRT', 'SOC', 'SOS', 'SPCE', 'SPRO', 'SPWH', 'SRFM', 'SRG', 'SSP', 'SSTK', 'STEM', 'STKE', 'STLA', 'SVRA', 'TBLA', 'TCPC', 'TDUP', 'TE', 'TGE', 'TIGR', 'TLRY', 'TMC', 'TMCI', 'TPVG', 'TRAD-RI', 'TROX', 'TSHA', 'TTEC', 'TUYA', 'TV', 'UA', 'UAA', 'UAMY', 'UIS', 'ULCC', 'UPB', 'UWMC', 'VFS', 'VLN', 'VNET', 'VTEX', 'VVR', 'VYGR', 'WDH', 'WENC-RI', 'WIT', 'WOOF', 'WTI', 'XNET']

In [19]:
page4 = ['XNET', 'XPOF', 'XRX', 'XTND', 'YCY-WT', 'YRD', 'ZH', 'ZIP', 'ZVIA']

In [31]:
#Combine all tickers from each page
all_tickers = [page1, page2, page3, page4]

In [32]:
# remove duplicate tickers
tickers = list(dict.fromkeys(
    ticker.strip().upper()
    for page in all_tickers
    for ticker in page
    if ticker.strip()
))
print('Total unique tickers: ', len(tickers))

Total unique tickers:  308

In [33]:
start_date = "2020-01-01"
end_date = "2026-01-01"

In [34]:
base_dir = Path('penny_stocks_research')
raw_dir = base_dir / 'raw'
raw_dir.mkdir(parents=True, exist_ok=True)
print('Saving files in:', base_dir.resolve())

Saving files in: C:\Users\erick\Desktop\penny_stocks\penny_stocks_research

In [58]:
#testing yf for data collection
test = yf.Ticker("SNDL").history(
    start=start_date,
    end=end_date,
    interval="1d",
    auto_adjust=False,
    actions=True
)

display(test.head(5))

print("Number of rows:", len(test))
print("Columns:", test.columns.tolist())

,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits
Date,,,,,,,,
2020-01-02 00:00:00-05:00,31.0,33.599998,26.799999,30.299999,30.299999,296000,0.0,0.0
2020-01-03 00:00:00-05:00,28.4,30.000000,28.100000,28.900000,28.900000,82070,0.0,0.0
2020-01-06 00:00:00-05:00,28.6,30.500000,28.100000,29.700001,29.700001,69740,0.0,0.0
2020-01-07 00:00:00-05:00,29.6,30.200001,27.350000,28.400000,28.400000,64350,0.0,0.0
2020-01-08 00:00:00-05:00,29.1,29.400000,26.100000,27.100000,27.100000,101630,0.0,0.0

Number of rows: 1508
Columns: ['Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume', 'Dividends', 'Stock Splits']

In [55]:
# Downloading tickers
all_stocks=[]
download_log=[]

for i, ticker in enumerate(tickers , start=1):
    print(f"{i}/308: {ticker}")
    try:
        history= yf.Ticker(ticker).history(
            start=start_date,
            end=end_date,
            interval='1d',
            auto_adjust=False,
            actions=True,
            repair=True
        )
        if history.empty:
            download_log.append({
                'ticker': ticker ,
                'statues': 'EMPTY',
                'rows':0
            })
            continue
        history.index = pd.to_datetime(history.index)
        if history.index.tz is not None:
            history.index = history.index.tz_localize(None)
        history.index.name = 'date'
        df = history.reset_index()
        df['ticker'] = ticker
        df.to_csv(raw_dir / f'{ticker}.csv', index=False)

        all_stocks.append(df)
        download_log.append({
            'ticker':ticker,
            'status':'OK',
            'rows': len(df)
        })
    except Exception as e:
        print('Error:', ticker,str(e))
        download_log.append({
            'ticker':ticker,
            'status':'Failed',
            'rows':0
        })
log_df = pd.DataFrame(download_log)
display(log_df)
log_df.to_csv(base_dir / 'download_log.csv', index=True)

if all_stocks:
    panel = pd.concat(all_stocks, ignore_index=True)
    panel = panel.sort_values(['ticker','date'])
    panel.to_csv( base_dir / 'historical_stock_data.csv', index=False)
    print('Total observations:', len(panel))
    print('Succefully downloaded', len(all_stocks))
    display(panel.head())
else:
    print('No data downloaded. Check for errors in the code')

1/100: ABEV
2/100: ABOS
3/100: ABR
4/100: ABUS
5/100: ACCO
6/100: ACDC
7/100: ACH
8/100: ACHR
9/100: ACP
10/100: ACRE
11/100: ACRS
12/100: ADCT
13/100: AIV
14/100: ALEC
15/100: ALLO
16/100: ALXO
17/100: AMBP
18/100: AMC
19/100: AMPY
20/100: AMTD
21/100: ANGX
22/100: ANNX
23/100: ANTX
24/100: ANVS
25/100: API
26/100: ASG

$ASGI-RI: possibly delisted; no price data found  (1d 2020-01-01 -> 2026-01-01)

27/100: ASGI-RI
28/100: AUR
29/100: AUTL
30/100: AVAL
31/100: AVD
32/100: AVIR
33/100: AVXL
34/100: BAK
35/100: BBAI

$BBBYW: possibly delisted; no price data found  (1d 2020-01-01 -> 2026-01-01) (Yahoo error = "Data doesn't exist for startDate = 1577854800, endDate = 1767243600")

36/100: BBBYW
37/100: BBD
38/100: BBDO

$BCAT-RI: possibly delisted; no price data found  (1d 2020-01-01 -> 2026-01-01)

39/100: BCAT-RI
40/100: BCYC
41/100: BDN
42/100: BDTX
43/100: BGS
44/100: BHR
45/100: BIRD
46/100: BLND
47/100: BMEA
48/100: BORR
49/100: BRSP
50/100: BUR
51/100: BW
52/100: BZUN
53/100: CABA
54/100: CANG
55/100: CCCC
56/100: CCIF
57/100: CCO
58/100: CDXS
59/100: CGC
60/100: CHGG
61/100: CIG
62/100: CLNE
63/100: CLOV
64/100: CLVT
65/100: CMTG
66/100: CMTL
67/100: CNDT
68/100: COTY
69/100: COUR
70/100: CRBU
71/100: CRMT
72/100: CRNT

$CSHR: possibly delisted; no price data found  (1d 2020-01-01 -> 2026-01-01) (Yahoo error = "Data doesn't exist for startDate = 1577854800, endDate = 1767243600")

73/100: CSHR
74/100: CTMX
75/100: CVGI
76/100: CVRX
77/100: CWH
78/100: CYH
79/100: DDD
80/100: DDL
81/100: DHF
82/100: DHX
83/100: DNUT
84/100: DOUG
85/100: DSX
86/100: DWSN
87/100: EARN
88/100: ECC
89/100: EDF
90/100: EDIT
91/100: EGHT
92/100: EHTH
93/100: ELME

$ENHA: possibly delisted; no price data found  (1d 2020-01-01 -> 2026-01-01) (Yahoo error = "Data doesn't exist for startDate = 1577854800, endDate = 1767243600")

94/100: ENHA
95/100: ENIC
96/100: ENVX
97/100: ESRT
98/100: EVEX
99/100: EVGO
100/100: EVH
101/100: EVO
102/100: EVTL
103/100: EXFY
104/100: FEAM
105/100: FINV
106/100: FIP
107/100: FLWS
108/100: FLX
109/100: FPH
110/100: FRMI
111/100: FSCO
112/100: GCTS
113/100: GDRX
114/100: GEMI
115/100: GERN
116/100: GETY
117/100: GGT
118/100: GLAS
119/100: GLOO
120/100: GME-WT

$GME-WT: possibly delisted; no price data found  (1d 2020-01-01 -> 2026-01-01)

121/100: GOGO
122/100: GOTU
123/100: GPRO
124/100: GRAB
125/100: GRNT
126/100: GSIT
127/100: GT
128/100: GTM
129/100: GTN
130/100: HCAT
131/100: HEPS
132/100: HIO
133/100: HIX
134/100: HKD
135/100: HLLY
136/100: HRZN
137/100: HTT
138/100: HTZ
139/100: HUMA
140/100: HUYA
141/100: ICL
142/100: IFRX
143/100: IHRT
144/100: IMSR
145/100: IQ
146/100: IRWD
147/100: JBI
148/100: JBLU
149/100: JELD
150/100: JOBY
151/100: JQC
152/100: JRVR
153/100: KLC
154/100: KLTR
155/100: KNDI
156/100: KOS
157/100: KPTI
158/100: LAB
159/100: LAC
160/100: LAES
161/100: LAR
162/100: LCID
163/100: LDI
164/100: LENZ
165/100: LGO
166/100: LOT
167/100: LPL
168/100: LU
169/100: LX
170/100: LZM
171/100: MBI
172/100: MERC
173/100: METCB
174/100: MFM
175/100: MGNX
176/100: MGX
177/100: MIST
178/100: MLCO
179/100: MMT
180/100: MOMO
181/100: MPT
182/100: MX
183/100: MXCT
184/100: MYGN
185/100: NABL
186/100: NCMI
187/100: NFE
188/100: NIO
189/100: NKTX

$NMCO-RI: possibly delisted; no price data found  (1d 2020-01-01 -> 2026-01-01)

190/100: NMCO-RI
191/100: NMG
192/100: NMRA
193/100: NNBR
194/100: NPWR
195/100: NRGV
196/100: NRO
197/100: NUVB
198/100: NXDR

$OCAC-RI: possibly delisted; no price data found  (1d 2020-01-01 -> 2026-01-01)

199/100: NXH
200/100: OCAC-RI
201/100: OGG
202/100: OGI
203/100: ONL
204/100: OPEN
205/100: OPENL
206/100: OPENW
207/100: OPENZ
208/100: OPK
209/100: OPTU
210/100: OSUR
211/100: OWLT
212/100: OXSQ
213/100: PACB
214/100: PACK
215/100: PAL
216/100: PEPG
217/100: PERF
218/100: PETS
219/100: PEW
220/100: PHK
221/100: PLCE
222/100: PLRX
223/100: PLTK
224/100: PMVP
225/100: PNNT
226/100: PRLD
227/100: PSEC
228/100: PTLO
229/100: PYXS
230/100: QS
231/100: RBBN
232/100: RC
233/100: RCS
234/100: RERE
235/100: RGP
236/100: RLX
237/100: RWT
238/100: RXRX
239/100: RXT
240/100: SABR
241/100: SANA
242/100: SEATW
243/100: SES
244/100: SFIX
245/100: SID
246/100: SITC
247/100: SJT

$SKYD-WT: possibly delisted; no price data found  (1d 2020-01-01 -> 2026-01-01)
$SKYD-WT-WI: possibly delisted; no price data found  (1d 2020-01-01 -> 2026-01-01)

248/100: SKYD-WT
249/100: SKYD-WT-WI
250/100: SLDP
251/100: SLQT
252/100: SMRT
253/100: SOC
254/100: SOS
255/100: SPCE
256/100: SPRO
257/100: SPWH
258/100: SRFM
259/100: SRG
260/100: SSP
261/100: SSTK
262/100: STEM
263/100: STKE
264/100: STLA
265/100: SVRA
266/100: TBLA
267/100: TCPC
268/100: TDUP
269/100: TE
270/100: TGE
271/100: TIGR
272/100: TLRY
273/100: TMC
274/100: TMCI
275/100: TPVG

$TRAD-RI: possibly delisted; no price data found  (1d 2020-01-01 -> 2026-01-01)

276/100: TRAD-RI
277/100: TROX
278/100: TSHA
279/100: TTEC
280/100: TUYA
281/100: TV
282/100: UA
283/100: UAA
284/100: UAMY
285/100: UIS
286/100: ULCC
287/100: UPB
288/100: UWMC
289/100: VFS
290/100: VLN
291/100: VNET
292/100: VTEX
293/100: VVR
294/100: VYGR
295/100: WDH

$WENC-RI: possibly delisted; no price data found  (1d 2020-01-01 -> 2026-01-01)

296/100: WENC-RI
297/100: WIT
298/100: WOOF
299/100: WTI
300/100: XNET
301/100: XPOF
302/100: XRX
303/100: XTND

$XTND: possibly delisted; no price data found  (1d 2020-01-01 -> 2026-01-01) (Yahoo error = "Data doesn't exist for startDate = 1577854800, endDate = 1767243600")
$YCY-WT: possibly delisted; no price data found  (1d 2020-01-01 -> 2026-01-01)

304/100: YCY-WT
305/100: YRD
306/100: ZH
307/100: ZIP
308/100: ZVIA

     ticker status  rows statues
0      ABEV     OK  1508     NaN
1      ABOS     OK  1131     NaN
2       ABR     OK  1508     NaN
3      ABUS     OK  1508     NaN
4      ACCO     OK  1508     NaN
..      ...    ...   ...     ...
303  YCY-WT    NaN     0   EMPTY
304     YRD     OK  1508     NaN
305      ZH     OK  1198     NaN
306     ZIP     OK  1156     NaN
307    ZVIA     OK  1117     NaN

[308 rows x 4 columns]

Total observations: 386179
Succefully downloaded 294

,date,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits,Repaired?,ticker
0,2020-01-02,4.67,4.73,4.67,4.73,3.632919,10162700,0.0,0.0,False,ABEV
1,2020-01-03,4.64,4.70,4.63,4.67,3.586834,8742700,0.0,0.0,False,ABEV
2,2020-01-06,4.61,4.69,4.59,4.62,3.548432,12846500,0.0,0.0,False,ABEV
3,2020-01-07,4.60,4.70,4.58,4.63,3.556112,13782900,0.0,0.0,False,ABEV
4,2020-01-08,4.63,4.69,4.59,4.64,3.563793,18280200,0.0,0.0,False,ABEV

In [56]:
if all_stocks:
    print("Dataset shape:", panel.shape)
    print("\nStocks collected:", panel["ticker"].nunique())
    print("\nMissing values:")
    display(panel.isna().sum().to_frame("missing_values"))

    print("\nObservations per ticker:")
    display(
        panel.groupby("ticker")
        .size()
        .sort_values()
        .to_frame("observations")
    )

Dataset shape: (386179, 11)

Stocks collected: 294

Missing values:

              missing_values
date                       0
Open                       0
High                       0
Low                        0
Close                      0
Adj Close                  0
Volume                     0
Dividends                  0
Stock Splits               0
Repaired?                  0
ticker                     0

Observations per ticker:

        observations
ticker
OPENW              6
OPENL              6
OPENZ              6
GLOO              30
FRMI              64
...              ...
AVAL            1508
AMPY            1508
AMTD            1508
ABR             1508
ABEV            1508

[294 rows x 1 columns]

In [4]:
panel = pd.read_csv('penny_stocks_research/historical_stock_data.csv')

In [5]:
panel

,date,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits,Repaired?,ticker
0,2020-01-02,4.67,4.730,4.670,4.73,3.632919,10162700,0.0,0.0,False,ABEV
1,2020-01-03,4.64,4.700,4.630,4.67,3.586834,8742700,0.0,0.0,False,ABEV
2,2020-01-06,4.61,4.690,4.590,4.62,3.548432,12846500,0.0,0.0,False,ABEV
3,2020-01-07,4.60,4.700,4.580,4.63,3.556112,13782900,0.0,0.0,False,ABEV
4,2020-01-08,4.63,4.690,4.590,4.64,3.563793,18280200,0.0,0.0,False,ABEV
...,...,...,...,...,...,...,...,...,...,...,...
386174,2025-12-24,2.32,2.360,2.235,2.29,2.290000,360600,0.0,0.0,False,ZVIA
386175,2025-12-26,2.27,2.320,2.270,2.28,2.280000,883500,0.0,0.0,False,ZVIA
386176,2025-12-29,2.27,2.335,2.270,2.32,2.320000,787200,0.0,0.0,False,ZVIA
386177,2025-12-30,2.32,2.330,2.270,2.31,2.310000,1114700,0.0,0.0,False,ZVIA
386178,2025-12-31,2.28,2.330,2.260,2.32,2.320000,2645700,0.0,0.0,False,ZVIA

In [6]:
# Use your existing combined DataFrame
panel = panel.copy()
panel["date"] = pd.to_datetime(panel["date"])

coverage = (
    panel.groupby("ticker")
    .agg(
        observations=("date", "nunique"),
        first_date=("date", "min"),
        last_date=("date", "max"),
        median_close=("Close", "median"),
        median_volume=("Volume", "median")
    )
    .reset_index()
    .sort_values("observations")
)

print("Total tickers:", len(coverage))
print("\nObservation-count summary:")
display(coverage["observations"].describe())

print("\nCoverage by threshold:")
for threshold in [60, 252, 500, 1000, 1250]:
    count = (coverage["observations"] >= threshold).sum()
    print(f"{threshold:4d}+ observations: {count} tickers")

Total tickers: 294

Observation-count summary:

count     294.000000
mean     1313.534014
std       329.189890
min         6.000000
25%      1195.500000
50%      1508.000000
75%      1508.000000
max      1508.000000
Name: observations, dtype: float64

Coverage by threshold:
  60+ observations: 290 tickers
 252+ observations: 286 tickers
 500+ observations: 279 tickers
1000+ observations: 265 tickers
1250+ observations: 210 tickers

In [7]:
coverage

    ticker  observations first_date  last_date  median_close  median_volume
197  OPENW             6 2025-12-23 2025-12-31        0.9305       294750.0
196  OPENL             6 2025-12-23 2025-12-31        0.5430       400200.0
198  OPENZ             6 2025-12-23 2025-12-31        0.3910       393850.0
113   GLOO            30 2025-11-18 2025-12-31        7.2375       137100.0
104   FRMI            64 2025-10-01 2025-12-31       18.3550      4392350.0
..     ...           ...        ...        ...           ...            ...
28    AVAL          1508 2020-01-02 2025-12-31        3.2650        82150.0
18    AMPY          1508 2020-01-02 2025-12-31        5.5550       540950.0
19    AMTD          1508 2020-01-02 2025-12-31        5.1600        12433.5
2      ABR          1508 2020-01-02 2025-12-31       13.8500      2151650.0
0     ABEV          1508 2020-01-02 2025-12-31        2.6600     22607400.0

[294 rows x 6 columns]

In [8]:
# keeping stocks with more than 252 observations(1 bussines year)
eligible_tickers = coverage.loc[coverage['observations'] >=252, 'ticker'].tolist()

In [20]:
#filter tickers
panel_filtered = panel[panel['ticker'].isin(eligible_tickers)]
# save them into a csv file
panel_filtered.to_csv('penny_stocks_research/historical_stock_data_252days.csv', index=False)

In [30]:
panel_filtered.head(5)

,date,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits,Repaired?,ticker
0,2020-01-02,4.67,4.73,4.67,4.73,3.632919,10162700,0.0,0.0,False,ABEV
1,2020-01-03,4.64,4.70,4.63,4.67,3.586834,8742700,0.0,0.0,False,ABEV
2,2020-01-06,4.61,4.69,4.59,4.62,3.548432,12846500,0.0,0.0,False,ABEV
3,2020-01-07,4.60,4.70,4.58,4.63,3.556112,13782900,0.0,0.0,False,ABEV
4,2020-01-08,4.63,4.69,4.59,4.64,3.563793,18280200,0.0,0.0,False,ABEV

In [23]:
price_summary = (
    panel_filtered.groupby("ticker")
    .agg(
        observations=("Close", "count"),
        pct_days_below_5=(
            "Close",
            lambda s: 100 * (s <= 5).mean()
        ),
        median_close=("Close", "median"),
        median_volume=("Volume", "median")
    )
    .reset_index()
)

# Review stocks that stayed at or below $5 on most observed days
display(
    price_summary.sort_values(
        "pct_days_below_5",
        ascending=False
    ).head(30)
)

    ticker  observations  pct_days_below_5  median_close  median_volume
0     ABEV          1508        100.000000      2.660000     22607400.0
273    VVR          1508        100.000000      3.940000       636200.0
56     CIG          1508        100.000000      1.860000      4493775.0
276    WIT          1508        100.000000      2.770000      3968100.0
75     DHF          1508        100.000000      2.550000       377800.0
226  SEATW          1255        100.000000      1.500000         1700.0
80    DWSN          1508        100.000000      1.800000        14100.0
52     CCO          1508        100.000000      1.520000      1963000.0
3     ABUS          1508         99.933687      3.020000       929400.0
126    HTT          1508         99.867374      1.845000       799200.0
88    ENIC          1508         99.867374      2.990000       527900.0
106   GERN          1508         99.801061      1.810000      4057350.0
67    CRNT          1508         98.474801      2.360000       442700.0
192    OPK          1508         97.546419      1.660000      3360550.0
247   SVRA          1508         96.883289      2.330000       443100.0
34    BBDO          1508         96.883289      2.940000        19450.0
184    NRO          1508         96.883289      3.406489       157969.0
196   OXSQ          1508         96.153846      3.050000       251450.0
275    WDH          1169         95.295124      1.400000       250500.0
264   UAMY          1508         95.291777      0.460000       413450.0
79     DSX          1508         94.098143      2.940000       515959.0
33     BBD          1508         93.302387      3.380000     26611150.0
120   HEPS          1131         92.484527      1.930000       440400.0
143   KLTR          1118         92.039356      1.870000       204650.0
131   IFRX          1508         91.777188      2.485000       216350.0
186   NXDR          1041         89.337176      2.330000      1490800.0
220    RLX          1242         87.600644      2.135000      5486950.0
213   PYXS          1062         87.476460      2.547500       283800.0
279   XNET          1508         86.604775      2.120000       206800.0
254    TMC          1082         86.598891      1.375000      1543000.0

Observations:

- Historical coverage: Most displayed stocks have 1,508 observations.

- Historical price eligibility: several stocks were below or equal to $5 on 100% of their observed days.

- Liquidity varies substantially: Low volume can make price changes noisier, and trading strategies harder to execute. As observed, ABEV has median daily volume of about 22.6 million shares, while SEATW has only 1,700.

In [25]:
# saving price summary
price_summary.to_csv(
    "historical_price_summary.csv",
    index=False
)

In [28]:
panel["dollar_volume"] = panel["Close"] * panel["Volume"]

liquidity_summary = (
    panel.groupby("ticker")
    .agg(
        observations=("Close", "count"),
        pct_days_below_5=(
            "Close", lambda s: 100 * (s <= 5).mean()
        ),
        median_close=("Close", "median"),
        median_share_volume=("Volume", "median"),
        median_dollar_volume=("dollar_volume", "median")
    )
    .reset_index()
)

display(
    liquidity_summary.sort_values(
        "median_dollar_volume", ascending=False
    ).head(5)
)

,ticker,observations,pct_days_below_5,median_close,median_share_volume,median_dollar_volume
181,NIO,1508,25.928382,9.060,54087850.0,5.275789e+08
155,LCID,1328,0.000000,72.250,2844260.0,2.136577e+08
141,JBLU,1508,14.854111,7.915,11271800.0,9.765133e+07
17,AMC,1508,30.039788,42.850,5904115.0,9.428180e+07
34,BBD,1508,93.302387,3.380,26611150.0,9.344859e+07

In [29]:
panel

,date,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits,Repaired?,ticker,dollar_volume
0,2020-01-02,4.67,4.730,4.670,4.73,3.632919,10162700,0.0,0.0,False,ABEV,4.806957e+07
1,2020-01-03,4.64,4.700,4.630,4.67,3.586834,8742700,0.0,0.0,False,ABEV,4.082841e+07
2,2020-01-06,4.61,4.690,4.590,4.62,3.548432,12846500,0.0,0.0,False,ABEV,5.935083e+07
3,2020-01-07,4.60,4.700,4.580,4.63,3.556112,13782900,0.0,0.0,False,ABEV,6.381483e+07
4,2020-01-08,4.63,4.690,4.590,4.64,3.563793,18280200,0.0,0.0,False,ABEV,8.482013e+07
...,...,...,...,...,...,...,...,...,...,...,...,...
386174,2025-12-24,2.32,2.360,2.235,2.29,2.290000,360600,0.0,0.0,False,ZVIA,8.257740e+05
386175,2025-12-26,2.27,2.320,2.270,2.28,2.280000,883500,0.0,0.0,False,ZVIA,2.014380e+06
386176,2025-12-29,2.27,2.335,2.270,2.32,2.320000,787200,0.0,0.0,False,ZVIA,1.826304e+06
386177,2025-12-30,2.32,2.330,2.270,2.31,2.310000,1114700,0.0,0.0,False,ZVIA,2.574957e+06
386178,2025-12-31,2.28,2.330,2.260,2.32,2.320000,2645700,0.0,0.0,False,ZVIA,6.138024e+06

In [31]:
# save them into a csv file
panel_filtered.to_csv('penny_stocks_research/historical_stock_data_252days_dollarvolume.csv', index=False)